// 'use client';
import './globals.css';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // global-erro.tsxのテスト
  // if (new Date().getMinutes() == 49) {
  //   throw new Error('global error test');
  // }
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="bg-emerald-300">hahaha</h1>
        {children}
      </body>
    </html>
  );
}
